### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by Niemi** [facebookarchive/webscalesql-5.6#1]
after running build #./BUILD/compile-pentium --prefix=/var/lib/mysql
Linux localhost.localdomain 3.14.0-0.rc7.git0.1.fc21.i686 #1 SMP Mon Mar 17 14:09:52 UTC 2014 i686 i686 i386 GNU/Linux
$ rpm -qa |grep bison
bison-3.0.2-1.fc21.i686
$ rpm -qa |grep cmake
cmake-3.0.0-0.5.rc3.fc21.i686
]$ rpm -qa |grep gcc
libgcc-4.8.2-14.fc21.i686
gcc-c++-4.8.2-14.fc21.i686
## gcc-4.8.2-14.fc21.i686

Fedora release 21 (Rawhide)
NAME=Fedora
VERSION="21 (Rawhide)"
ID=fedora
VERSION_ID=21
PRETTY_NAME="Fedora 21 (Rawhide)"
===================[part of error output in console]==============
           /\* nothing _/     { Lex->xa_opt=XA_NONE;        }
       ^
/home/niemi/webscale56/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/niemi/webscale56/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/niemi/webscale56/sql/sql_yacc.yy:16547:7: note: in expansion of macro ‘Lex’
         | ONE_SYM PHASE_SYM { Lex->xa_opt=XA_ONE_PHASE;   }
       ^
/home/niemi/webscale56/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/niemi/webscale56/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/niemi/webscale56/sql/sql_yacc.yy:16552:7: note: in expansion of macro ‘Lex’
           { Lex->xa_opt=XA_NONE;        }
       ^
/home/niemi/webscale56/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/niemi/webscale56/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/niemi/webscale56/sql/sql_yacc.yy:16554:7: note: in expansion of macro ‘Lex’
           { Lex->xa_opt=XA_SUSPEND;     }
       ^
/home/niemi/webscale56/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/niemi/webscale56/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/niemi/webscale56/sql/sql_yacc.yy:16560:7: note: in expansion of macro ‘Lex’
         | FOR_SYM MIGRATE_SYM { Lex->xa_opt=XA_FOR_MIGRATE; }
       ^
/home/niemi/webscale56/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/niemi/webscale56/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/niemi/webscale56/sql/sql_yacc.yy:16566:23: note: in expansion of macro ‘Lex’
             LEX *lex= Lex;
                       ^
/home/niemi/webscale56/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/niemi/webscale56/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/niemi/webscale56/sql/sql_yacc.yy:16576:23: note: in expansion of macro ‘Lex’
             LEX *lex= Lex;
                       ^
make[2]: *_\* [sql/CMakeFiles/sql.dir/sql_yacc.cc.o] Error 1
make[1]: **\* [sql/CMakeFiles/sql.dir/all] Error 2

**Comment by steaphan-fb-com** [comment]
I believe this is the issue being addressed in this proposed diff:

https://reviews.facebook.net/D17229

Basically, upstream MySQL's yacc is not compatible with bison version 3+.

Hopefully, once this diff is completed and pushed, this problem will be fixed.

**Comment by chipturner** [comment]
Yep, that should fix your issue; it's actually an upstream issue not fixed
in 5.6.16 afaik.  You can test it via 'arc patch D17229' to get my diff
into your local git repo (details for getting arc working are on our
contribution page, http://webscalesql.org/contributing.html ).

On Fri, Mar 28, 2014 at 4:22 AM, Steaphan Greene
notifications@github.comwrote:

> I believe this is the issue being addressed in this proposed diff:
> 
> https://reviews.facebook.net/D17229
> 
> Basically, upstream MySQL's yacc is not compatible with bison version 3+.
> 
> Hopefully, once this diff is completed and pushed, this problem will be
> fixed.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/webscalesql/webscalesql-5.6/issues/1#issuecomment-38909367
> .

## 

Chip Turner - cturner@pattern.net

**Comment by steaphan-fb-com** [comment]
This fix is now pushed in the webscalesql-5.6.17 branch, so this should be solved.  Please open a new issue if there are still problems with this.

**Comment by dpaks** [comment]
Hello, I am new to Ubuntu. Pardon my mistakes, if any. I'm trying to install MySQL from source tree. I have compiled and built it. While trying to install it using 'make install', I am getting the following errors: 

> make[2]: **\* [sql/CMakeFiles/sql.dir/sql_yacc.cc.o] Error 1 
> 
> make[1]: **\* [sql/CMakeFiles/sql.dir/all] Error 2
> 
> make: **\* [all] Error 2

The compilation commands were:

> cmake ..
> 
> cmake --build .
> 
> sudo make install

The compilation log is:

``````
home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16486:13: note: in expansion of macro ‘Lex’
             Lex->current_select()->table_list.push_front(&Lex->save_list);
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16492:7: note: in expansion of macro ‘Lex’
           { Lex->create_view_check= VIEW_CHECK_NONE; }
       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16494:7: note: in expansion of macro ‘Lex’
           { Lex->create_view_check= VIEW_CHECK_CASCADED; }
       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16496:7: note: in expansion of macro ‘Lex’
           { Lex->create_view_check= VIEW_CHECK_CASCADED; }
       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16498:7: note: in expansion of macro ‘Lex’
           { Lex->create_view_check= VIEW_CHECK_LOCAL; }
       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16541:23: note: in expansion of macro ‘YYTHD’
             THD *thd= YYTHD;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16591:23: note: in expansion of macro ‘YYTHD’
             THD *thd= YYTHD;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16626:23: note: in expansion of macro ‘YYTHD’
             THD *thd= YYTHD;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16644:23: note: in expansion of macro ‘YYTHD’
             THD *thd= YYTHD;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16666:23: note: in expansion of macro ‘YYTHD’
             THD *thd= YYTHD;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16690:13: note: in expansion of macro ‘Lex’
             Lex->sphead->m_parser_data.set_parameter_end_ptr(@6.start);
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16694:23: note: in expansion of macro ‘Lex’
             LEX *lex= Lex;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16702:23: note: in expansion of macro ‘Lex’
             LEX *lex= Lex;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16725:23: note: in expansion of macro ‘YYTHD’
             THD *thd= YYTHD;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16733:23: note: in expansion of macro ‘YYTHD’
             THD *thd= YYTHD;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16792:23: note: in expansion of macro ‘YYTHD’
             THD *thd= YYTHD;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16812:13: note: in expansion of macro ‘Lex’
             Lex->sphead->m_parser_data.set_parameter_start_ptr(@4.end);
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16817:23: note: in expansion of macro ‘YYTHD’
             THD *thd= YYTHD;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16825:23: note: in expansion of macro ‘YYTHD’
             THD *thd= YYTHD;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16833:23: note: in expansion of macro ‘YYTHD’
             THD *thd= YYTHD;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16847:13: note: in expansion of macro ‘Lex’
             Lex->sql_command = SQLCOM_XA_START;
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16851:13: note: in expansion of macro ‘Lex’
             Lex->sql_command = SQLCOM_XA_END;
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16855:13: note: in expansion of macro ‘Lex’
             Lex->sql_command = SQLCOM_XA_PREPARE;
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16859:13: note: in expansion of macro ‘Lex’
             Lex->sql_command = SQLCOM_XA_COMMIT;
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16863:13: note: in expansion of macro ‘Lex’
             Lex->sql_command = SQLCOM_XA_ROLLBACK;
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16867:13: note: in expansion of macro ‘Lex’
             Lex->sql_command = SQLCOM_XA_RECOVER;
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:102:40: note: in expansion of macro ‘YYTHD’
     LEX::cleanup_lex_after_parse_error(YYTHD);\
                                        ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:110:5: note: in expansion of macro ‘MYSQL_YYABORT’
     MYSQL_YYABORT;                      \
     ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16874:13: note: in expansion of macro ‘MYSQL_YYABORT_UNLESS’
             MYSQL_YYABORT_UNLESS($1->length() <= MAXGTRIDSIZE);
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16875:19: note: in expansion of macro ‘Lex’
             if (!(Lex->xid=(XID *)YYTHD->alloc(sizeof(XID))))
                   ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16877:13: note: in expansion of macro ‘Lex’
             Lex->xid->set(1L, $1->ptr(), $1->length(), 0, 0);
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:102:40: note: in expansion of macro ‘YYTHD’
     LEX::cleanup_lex_after_parse_error(YYTHD);\
                                        ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:110:5: note: in expansion of macro ‘MYSQL_YYABORT’
     MYSQL_YYABORT;                      \
     ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16881:13: note: in expansion of macro ‘MYSQL_YYABORT_UNLESS’
             MYSQL_YYABORT_UNLESS($1->length() <= MAXGTRIDSIZE && $3->length() <= MAXBQUALSIZE);
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16882:19: note: in expansion of macro ‘Lex’
             if (!(Lex->xid=(XID *)YYTHD->alloc(sizeof(XID))))
                   ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16884:13: note: in expansion of macro ‘Lex’
             Lex->xid->set(1L, $1->ptr(), $1->length(), $3->ptr(), $3->length());
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:102:40: note: in expansion of macro ‘YYTHD’
     LEX::cleanup_lex_after_parse_error(YYTHD);\
                                        ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:110:5: note: in expansion of macro ‘MYSQL_YYABORT’
     MYSQL_YYABORT;                      \
     ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16888:13: note: in expansion of macro ‘MYSQL_YYABORT_UNLESS’
             MYSQL_YYABORT_UNLESS($1->length() <= MAXGTRIDSIZE && $3->length() <= MAXBQUALSIZE);
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16889:19: note: in expansion of macro ‘Lex’
             if (!(Lex->xid=(XID *)YYTHD->alloc(sizeof(XID))))
                   ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16891:13: note: in expansion of macro ‘Lex’
             Lex->xid->set($5, $1->ptr(), $1->length(), $3->ptr(), $3->length());
             ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16901:7: note: in expansion of macro ‘Lex’
           /* nothing */ { Lex->xa_opt=XA_NONE;        }
       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16902:7: note: in expansion of macro ‘Lex’
         | JOIN_SYM      { Lex->xa_opt=XA_JOIN;        }
       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16903:7: note: in expansion of macro ‘Lex’
         | RESUME_SYM    { Lex->xa_opt=XA_RESUME;      }
       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16907:7: note: in expansion of macro ‘Lex’
           /* nothing */     { Lex->xa_opt=XA_NONE;        }
       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16908:7: note: in expansion of macro ‘Lex’
         | ONE_SYM PHASE_SYM { Lex->xa_opt=XA_ONE_PHASE;   }
       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16913:7: note: in expansion of macro ‘Lex’
           { Lex->xa_opt=XA_NONE;        }
       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16915:7: note: in expansion of macro ‘Lex’
           { Lex->xa_opt=XA_SUSPEND;     }
       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16921:7: note: in expansion of macro ‘Lex’
         | FOR_SYM MIGRATE_SYM { Lex->xa_opt=XA_FOR_MIGRATE; }
       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16927:23: note: in expansion of macro ‘Lex’
             LEX *lex= Lex;
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:31:23: error: ‘yythd’ was not declared in this scope
 #define YYTHD ((THD *)yythd)
                       ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:39:14: note: in expansion of macro ‘YYTHD’
 #define Lex (YYTHD->lex)
              ^
/home/deepaks/bzr/mysql-server/mysql-5.7-build/sql/sql_yacc.yy:16937:23: note: in expansion of macro ‘Lex’
             LEX *lex= Lex;
                       ^
make[2]: *** [sql/CMakeFiles/sql.dir/sql_yacc.cc.o] Error 1
make[1]: *** [sql/CMakeFiles/sql.dir/all] Error 2
make: *** [all] Error 2```

I followed (http://dev.mysql.com/doc/refman/5.5/en/installing-source-distribution.html) to perform the previously mentioned steps.
I have updated bison to the latest as suggested in another forum. Kindly help. Thanks in advance.
``````
